spring.application.name=calendario-api
spring.datasource.url=jdbc:postgresql://localhost:5432/calendar
spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.username=postgres
# spring.datasource.password=Dayko17zppc
spring.datasource.username=calendar_user
spring.datasource.password=calendar_pass
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
festivos.api.url=${API_FESTIVOS_URL:http://localhost:3000/festivos/obtener/}

logging.level.org.hibernate.SQL=DEBUG