spring.application.name=calendario-api
spring.datasource.url=jdbc:postgresql://localhost:5432/calendar
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Dayko17zppc
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.org.hibernate.SQL=DEBUG